import { LABELS_STACKS } from "./stack-label";

export const COMPANY = [
    {
    name: "IROK / Genius At Work",
    location: "Tsiadana Antananarivo",
    stacks: [
      LABELS_STACKS.REACT_NATIVE,
      LABELS_STACKS.ANDROID,
      LABELS_STACKS.IOS,
      LABELS_STACKS.REDUX,
      LABELS_STACKS.JAVASCRIPT,
      LABELS_STACKS.FIREBASE,
      LABELS_STACKS.I18N,
      LABELS_STACKS.WEB_SOCKET,
      LABELS_STACKS.WEB_RTC,
      LABELS_STACKS.APP_STORE,
      LABELS_STACKS.PLAY_STORE,
      LABELS_STACKS.FIGMA,
      LABELS_STACKS.AGILE,
      LABELS_STACKS.JIRA,
    ],
  },
  {
    name: "AZ+",
    location: "Ambohimiandra Antananarivo",
    stacks: [
      LABELS_STACKS.REACT_NATIVE,
      LABELS_STACKS.ANDROID,
      LABELS_STACKS.IOS,
      LABELS_STACKS.CONTEXT,
      LABELS_STACKS.TYPESCRIPT,
      LABELS_STACKS.FIGMA,
      LABELS_STACKS.NEST_JS,
      LABELS_STACKS.REST_API,
      LABELS_STACKS.PRISMA,
      LABELS_STACKS.FIREBASE,
      LABELS_STACKS.MAPS,
      LABELS_STACKS.JWT,
      LABELS_STACKS.POSTGRE_SQL,
      LABELS_STACKS.AGILE,
      LABELS_STACKS.JIRA,
    ],
  },
  {
    name: "RELIA / AZ+",
    location: "Ambohimiandra Antananarivo",
    stacks: [
      LABELS_STACKS.REACT_NATIVE,
      LABELS_STACKS.ANDROID,
      LABELS_STACKS.IOS,
      LABELS_STACKS.RECOIL,
      LABELS_STACKS.TYPESCRIPT,
      LABELS_STACKS.FIGMA,
      LABELS_STACKS.FIREBASE,
      LABELS_STACKS.FIRESTORE,
      LABELS_STACKS.AGILE,
      LABELS_STACKS.JIRA,
    ],
  },
  {
    name: "Ministère des Mines à Madagascar",
    location: "",
    stacks: [
      LABELS_STACKS.PHP,
      LABELS_STACKS.PHP_WORD,
      LABELS_STACKS.PHP_QR,
      LABELS_STACKS.FPDF,
      LABELS_STACKS.JQUERY,
      LABELS_STACKS.BOOTSTRAP,
      LABELS_STACKS.TAILWIND_CSS,
      LABELS_STACKS.MYSQL,
    ],
  },
  {
    name: "Hellopro / Hellotana",
    location: "Antsahavola Antananarivo",
    stacks: [
      LABELS_STACKS.PHP,
      LABELS_STACKS.JQUERY,
      LABELS_STACKS.ZOHO,
      LABELS_STACKS.MYSQL,
    ],
  },
  {
    name: "Orange Madagascar",
    location: "La Tour Ankorondrano Antananarivo",
    stacks: [
      LABELS_STACKS.ANGULAR,
      LABELS_STACKS.JAVASCRIPT,
      LABELS_STACKS.QUARKUS,
      LABELS_STACKS.JAVA,
      LABELS_STACKS.REST_API,
      LABELS_STACKS.MYSQL,
    ],
  },
  {
    name: "BOA (Bank Of Africa)",
    location: "Tsianolondroa Fianarantsoa",
    stacks: [
      LABELS_STACKS.PHP,
      LABELS_STACKS.PHP_EXCEL,
      LABELS_STACKS.FPDF,
      LABELS_STACKS.JQUERY,
      LABELS_STACKS.BOOTSTRAP,
      LABELS_STACKS.MYSQL,
    ],
  },
];
